-- Wrap auth.uid() in RLS policy predicates in (SELECT ...) so Postgres evaluates it once
-- per statement (InitPlan) instead of once per row -- the Supabase-documented RLS perf
-- pattern. Predicate-equivalent (row visibility unchanged). Generated by
-- 'pgrls fix --rule PERF001' and verified (PERF001 -> 0). Refs #63.

-- [PERF001] Wrap auth function call(s) in policy 'api_keys_select' on public.api_keys so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY api_keys_select ON public.api_keys
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'document_chunks_select' on public.document_chunks so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY document_chunks_select ON public.document_chunks
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'documents_select' on public.documents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY documents_select ON public.documents
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'knowledge_bases_select' on public.knowledge_bases so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY knowledge_bases_select ON public.knowledge_bases
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'users_select' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY users_select ON public.users
    USING (id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'users_update' on public.users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY users_update ON public.users
    USING (id = (SELECT auth.uid()));
